### ISSUE TITLE
/usr/bin/env not available when running scripts from cron

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/srv_tools#11]
@coolaj86 I need your help on this project one more time. ;)

When I add the scripts to my `crontab`, they don't run because `/usr/bin/env node` doesn't work from cron. I believe the issue stems from cron having its own shell where the path isn't set.

```
/usr/bin/env: node: No such file or directory
```

What do you suggest?

**Comment by coolaj86** [comment]
You'll need to adjust cron's path and you might still need to set the shebang to /usr/local/bin/node manually.
